import type { NextPage } from 'next'
import Head from 'next/head'
import { Card } from '../src/components/Card'
import { mock } from '../src/components/Card/mock'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next Components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
      </main>

      <footer >
      </footer>
    </div>
  )
}

export default Home
